import streamlit as st
import json
from utils.logger import logger

def render_story_tab(agent, itinerary, user_name):
    """
    Renders an AI-generated travel story based on the user's itinerary.
    
    This tab creates a personalized narrative that brings the travel plan to life,
    transforming dry itinerary data into an engaging story that helps users
    visualize their upcoming adventure.
    
    Args:
        agent: The AI agent workflow instance with generate_story method
        itinerary: Dictionary containing the complete travel plan
        user_name: The traveler's name for personalization
    """
    st.subheader("📖 Your AI-Generated Travel Story")
    
    st.info("✨ This story is generated by AI to help you visualize and get excited about your upcoming trip!")
    
    try:
        # Initialize session state for story if not exists
        if "travel_story" not in st.session_state:
            st.session_state.travel_story = None
        
        # Check if we need to generate a new story
        # This happens when there's no story or when the itinerary has changed
        current_itinerary_hash = hash(json.dumps(itinerary, sort_keys=True, default=str))
        stored_hash = st.session_state.get("story_itinerary_hash")
        
        needs_regeneration = (
            st.session_state.travel_story is None or 
            stored_hash != current_itinerary_hash
        )
        
        # Add manual regenerate button
        col1, col2 = st.columns([3, 1])
        with col2:
            if st.button("🔄 Regenerate Story", help="Generate a new version of the story"):
                needs_regeneration = True
                st.session_state.travel_story = None
        
        if needs_regeneration:
            with st.spinner(f"✍️ Writing {user_name}'s personalized travel story..."):
                
                # Validate inputs
                if not itinerary:
                    st.warning("No itinerary data available. Please generate a travel plan first.")
                    return
                
                if not agent:
                    st.error("AI agent not initialized. Cannot generate story.")
                    return
                
                # Convert plan to text with error handling
                try:
                    plan_context = json.dumps(itinerary, default=str, indent=2)
                except (TypeError, ValueError) as e:
                    logger.warning(f"Failed to serialize itinerary: {e}")
                    plan_context = str(itinerary)
                
                # Validate user_name
                user_name_safe = user_name if user_name and user_name.strip() else "Traveler"
                
                # Call AI to generate story
                story_md = agent.generate_story(
                    plan_context=plan_context,
                    user_name=user_name_safe
                )
                
                # Validate story output
                if not story_md or not story_md.strip():
                    st.warning("The AI returned an empty story. Please try regenerating.")
                    logger.warning("Empty story returned from agent.generate_story()")
                    return
                
                # Save to session with hash for change detection
                st.session_state.travel_story = story_md
                st.session_state.story_itinerary_hash = current_itinerary_hash
                
                # Display the story
                st.markdown(story_md)
                
                # Add download option
                st.download_button(
                    label="📥 Download Story",
                    data=story_md,
                    file_name=f"{user_name_safe}_travel_story.md",
                    mime="text/markdown",
                    help="Download your travel story as a Markdown file"
                )
        else:
            # Show cached story
            st.markdown(st.session_state.travel_story)
            
            # Add download option for cached story too
            st.download_button(
                label="📥 Download Story",
                data=st.session_state.travel_story,
                file_name=f"{user_name if user_name else 'Traveler'}_travel_story.md",
                mime="text/markdown",
                help="Download your travel story as a Markdown file"
            )
            
    except Exception as e:
        logger.exception(f"Failed to generate story: {e}")
        st.error("❌ Could not generate travel story. Please try again or contact support.")
        
        # Show details in expander for debugging
        with st.expander("🔍 Error Details"):
            st.code(str(e))
            st.caption("If this error persists, please report it with the details above.")
